### ISSUE TITLE
Watch's the different of ’cochleagram_extractor_wdl‘ and 'cochleagram_extractor' in feature_extractor.py

### ISSUE THREAD

**Issue by zhucq** [ZhihaoDU/speech_feature_extractor#2]
Watch's the different of ’cochleagram_extractor_wdl‘ and 'cochleagram_extractor' in feature_extractor.py.
I mean I know , one of them make a sum and another use mean. But why ,what's the different used in them?
Thank you

**Comment by ZhihaoDU** [comment]
cochleagram_extractor_wdl is a special version of cochleagram_extractor, which is used for a paper posted by Prof. Deliang Wang. You just select one of them depending on the tasks on your hand.
