### ISSUE TITLE
"name 'mix_by_db' is not defined"

### ISSUE THREAD

**Issue by xdzhangxuejun** [ZhihaoDU/speech_feature_extractor#3]
Hi ZhihaoDU,
    I can't find the "mix_by_db", when ran speech_synthesis.py file. Can you give me some tips? Please share you dataset what you used in the work. Thank you very much!

**Comment by ZhihaoDU** [comment]
Sorry about that, I have fixed this issue. Please use the code in speech_utils.py and feature_extractor.py. The rest files are used when I developed this project.
