### ISSUE TITLE
How to use Gammatone IRM to synthesis the original signal? 

### ISSUE THREAD

**Issue by gao-shi** [ZhihaoDU/speech_feature_extractor#4]
I use function synthesis_speech in synthesis_speech.py to systhesis the original signal .
When i get the IRM which shape is (64, frame_num) , the code in the python file is 
`masked_abs = np.abs(stft[:win_len//2+1]) * mk[:, i]`  
using stft multiply the mask. It do not match this axis.  So the python file is only used to systhesis those masks extracted by stft, but not Gammatone filter?

**Comment by Huer-H** [comment]
> 我在Synthesis_speech.py​​中使用函数Synthesis_speech来合成原始信号。
> 当我得到形状为（64，frame_num）的IRM时，python文件中的代码
> `masked_abs = np.abs(stft[:win_len//2+1]) * mk[:, i]`
> 使用stft乘以掩码。它与该轴不匹配。因此，python文件仅用于合成由stft提取的那些蒙版，而不用于合成Gammatone过滤器吗？

My problem is the same as yours. How do you solve it?

**Comment by bailiangze** [comment]
我也是，怎么弄

**Comment by Huer-H** [comment]
是不是应该使用伽马通域的幅值谱*掩蔽值irm呢？

**Comment by ZhihaoDU** [comment]
Please use the code in speech_utils.py and feature_extractor.py. The rest files are used when I developed this project.
In speech_utils.py, coch_synthesis is used for the maskes defined on the cochleagram (extracted with gammatone filterbanks). While, synthesis_speech is used for the makes defined on the STFT domain.
